### ISSUE TITLE
Create a home page for the website

### ISSUE THREAD

**Issue by luckykumarirai** [luckykumarirai/easy-education#14]
Create a home page for the website with a better UI.

**Comment by Sloth-Panda** [comment]
tech stack? I can make it using html, css, js?

**Comment by soumya-badkul** [comment]
Hey @luckykumarirai , I would like to work on this issue

**Comment by luckykumarirai** [comment]
> tech stack? I can make it using html, css, js?

 I can only assign one issue at a time. first, you have to submit then I will assign some other issue.

**Comment by luckykumarirai** [comment]
> Hey @luckykumarirai , I would like to work on this issue

@soumya-badkul Go ahead! Using react-bootstrap, as a reference you can explore some educational or training websites.

**Comment by soumya-badkul** [comment]
@luckykumarirai do i need to use same navbar and footer?

**Comment by luckykumarirai** [comment]
> @luckykumarirai do i need to use same navbar and footer?

Yes

**Comment by luckykumarirai** [comment]
> > @luckykumarirai do i need to use same navbar and footer?
> 
> Yes

**Comment by soumya-badkul** [comment]
@luckykumarirai is this okay?
https://drive.google.com/file/d/1po_DElwi48eDBCryQDPlMArlg7hRw_G3/view?usp=sharing

**Comment by luckykumarirai** [comment]
> @luckykumarirai is this okay?
> https://drive.google.com/file/d/1po_DElwi48eDBCryQDPlMArlg7hRw_G3/view?usp=sharing

It' okay,  make sure it should responsive.

**Comment by soumya-badkul** [comment]
Yes it is
