### ISSUE TITLE
Design contact us page for website

### ISSUE THREAD

**Issue by luckykumarirai** [luckykumarirai/easy-education#22]
Design contact us page for website with dummy data right now using react-bootstrap.

**Comment by Devenkapoor7303** [comment]
can i work on this issue

**Comment by luckykumarirai** [comment]
@Devenkapoor7303 I can only assign one issue at a time first You have to make the PR that I have assign already then I can assign another issue to you.

**Comment by Devenkapoor7303** [comment]
Okay np

**Comment by soumya-badkul** [comment]
@luckykumarirai I would like to work on this issue. I have already created PR for my last issue

**Comment by luckykumarirai** [comment]
@soumya-badkul Go ahead!
