### ISSUE TITLE
Improve footer design.

### ISSUE THREAD

**Issue by luckykumarirai** [luckykumarirai/easy-education#23]
Make 4 columns it should be responsive.
### column-1 
- Mention ``` Easy Education``` with logo 
- email -easyeducation@gmail.com
- Address-IIIT Manipur,795002
### column-2  heading    will ```Company```
- about us
- term and condition
- privacy policy
- Blogs
### column-3 Heading will ```Learning and practice```
- Engineering
- Competitive exams
- Quiz
-  School
### column-4 
- contact us form with name and email and submit button

at the bottom add social media icons (Facebook, Linkedin, Twitter, Instagram, youtube) and copyright of things.
you can add a hover effect on these links. Try to implement attractive color combinations.

**Comment by Devenkapoor7303** [comment]
can i work on this issue

**Comment by luckykumarirai** [comment]
@Devenkapoor7303 Go ahead!

**Comment by Devenkapoor7303** [comment]
Is footer better or u can give me any suggestion
![Capture](https://user-images.githubusercontent.com/73438023/108343927-6003f200-7191-11eb-970d-c0e123a48a46.PNG)

**Comment by luckykumarirai** [comment]
> Is footer better or u can give me any suggestion
> ![Capture](https://user-images.githubusercontent.com/73438023/108343927-6003f200-7191-11eb-970d-c0e123a48a46.PNG)

I have described the issue now you can explore from the description.

**Comment by Devenkapoor7303** [comment]
Okay

**Comment by Devenkapoor7303** [comment]
Is it looking okay 

![Capture](https://user-images.githubusercontent.com/73438023/108543695-400c2580-729a-11eb-8d1c-2b9952e60190.PNG)

**Comment by kanishkaa24** [comment]
Hello Mam, Can I work on this?

**Comment by luckykumarirai** [comment]
> Is it looking okay
> 
> ![Capture](https://user-images.githubusercontent.com/73438023/108543695-400c2580-729a-11eb-8d1c-2b9952e60190.PNG)

Alignment of content is not even on both sides.
No need to mentation contact with us on the bottom only add social media icons in parallel to the copyright not above.
Remove these dotted lines from columns.

**Comment by Devenkapoor7303** [comment]
Okay I will make these changes and will make a PR
