### ISSUE TITLE
Design a logo for project.

### ISSUE THREAD

**Issue by luckykumarirai** [luckykumarirai/easy-education#3]

**Comment by raman-thakur** [comment]
i would like to design a logo for this project as a participant of CWOC . @luckykumarirai

**Comment by luckykumarirai** [comment]
@raman-thakur Go ahead!

**Comment by raman-thakur** [comment]
> @raman-thakur Go ahead!

okk

**Comment by luckykumarirai** [comment]
@raman-thakur are you still working?

**Comment by raman-thakur** [comment]
> @raman-thakur are you still working?

yes just give me one more day @luckykumarirai

**Comment by kanishkaa24** [comment]
Hello Mam, Can I work on this?
