### ISSUE TITLE
Design privacy and policy page 

### ISSUE THREAD

**Issue by luckykumarirai** [luckykumarirai/easy-education#33]
## Describe the solution you'd like
Design page with some dummy statements of privacy and policy.

## Additional context
Make simple with some attractive color combinations.

**Comment by soumya-badkul** [comment]
@luckykumarirai I would like to work on this

**Comment by luckykumarirai** [comment]
@soumya-badkul  Go ahead

**Comment by arbazalam01** [comment]
can i work on this issue

**Comment by kanishkaa24** [comment]
Hello Mam, Can I work on this?
