### ISSUE TITLE
Improve navbar 

### ISSUE THREAD

**Issue by luckykumarirai** [luckykumarirai/easy-education#40]
#### Add some shower effect on the button also.
Instead of Brand name Brand logo should be added in the navbar that present in public/images.
The First Main heading should be ```Engineering``` of the dropdown. Add some list of ```branch name``` of engineering like CSE, ECE.
### There will be another dropdown in   ```CSE```.
- DS(data structure)
- Algorithm
- Programming Language
- Core Subjects
- Web Technology
### Then the second heading should be ```School```.
- Class IX
- Class X
- Class XI
- Class XII
### The third heading should be ```competitive```.
- Quiz
- Bank
-  JEE Main
- Gate
-  SSC
### There should be two Buttons available in the navbar.
``` Sign up ```
- Student 
- Teacher
```Sign-in```
- Student
- Teacher

**Comment by raman-thakur** [comment]
I would like to work on this.

**Comment by raman-thakur** [comment]
What type of navbar you want, Can you describe ??

**Comment by luckykumarirai** [comment]
@raman-thakur  I can assign one issue at a time. You have to submit first then only I can assign.

**Comment by soumya-badkul** [comment]
@luckykumarirai I would like to work on this

**Comment by luckykumarirai** [comment]
@soumya-badkul Go ahead!

**Comment by soumya-badkul** [comment]
@luckykumarirai I'll be submitting the tomorrow, is that okay?

**Comment by luckykumarirai** [comment]
@soumya-badkul  No problem you can.

**Comment by soumya-badkul** [comment]
@luckykumarirai 
![image](https://user-images.githubusercontent.com/60295974/109480351-6e131600-7aa1-11eb-8bc7-09994f8ce498.png)
![image](https://user-images.githubusercontent.com/60295974/109480385-79fed800-7aa1-11eb-8ee4-8eb1a7cd2d4c.png)
![image](https://user-images.githubusercontent.com/60295974/109480486-9438b600-7aa1-11eb-8e3a-fda14588eb78.png)

**Comment by luckykumarirai** [comment]
@soumya-badkul make PR it's fine.
