### ISSUE TITLE
Improve home page design 

### ISSUE THREAD

**Issue by luckykumarirai** [luckykumarirai/easy-education#42]
Improve home page design using react-bootstrap.No need to attach the video on home, design with some better UI.

**Comment by raman-thakur** [comment]
I would like to work on this as a participant in CrossWOC. Can I??

**Comment by luckykumarirai** [comment]
@raman-thakur  Go ahead!

**Comment by raman-thakur** [comment]
which changes you want??
@luckykumarirai

**Comment by luckykumarirai** [comment]
> which changes you want??
> @luckykumarirai

You have to design a page with some images and dummy data in dark mode. no video should have on the home page.

**Comment by luckykumarirai** [comment]
> > which changes you want??
> > @luckykumarirai
> 
> You have to design a page with some images and dummy data in dark mode. no video should have on the home page.

**Comment by raman-thakur** [comment]
ok i will remove the vidio and i will add an cool image with low opacity! @luckykumarirai

**Comment by luckykumarirai** [comment]
@raman-thakur before making PR you can share one screenshot of your design according to that we will give some suggestions on what things need to add or remove.

**Comment by raman-thakur** [comment]
okk i will @luckykumarirai

**Comment by raman-thakur** [comment]
> @raman-thakur before making PR you can share one screenshot of your design according to that we will give some suggestions on what things need to add or remove.

pls review how this is looking???
https://1drv.ms/u/s!Ajesvg5LBV8RgWSnQiYYezPCa59U?e=oSsH9x

**Comment by raman-thakur** [comment]
@luckykumarirai

**Comment by luckykumarirai** [comment]
@raman-thakur Make PR.It should be responsive.
