### ISSUE TITLE
Design  Sign-up and sign-in page for teacher.

### ISSUE THREAD

**Issue by luckykumarirai** [luckykumarirai/easy-education#44]
Design signup and sign-in page for teacher login. 
Use an only react-bootstrap take care website is designing in dark so you have to design a page that suitable for the website.
It should be attractive with color combinations.
It should be responsive.

**Comment by arbazalam01** [comment]
can you assign this to me

**Comment by abhinav5481** [comment]
Hi
I can work on this. Please assign it to me

**Comment by luckykumarirai** [comment]
> Hi Lucky,
> I would like to work on this issue. If it is still open, could you please assign it to me?

@abhinav5481 sure
Go ahead

**Comment by abhinav5481** [comment]
Please assign it to me.

**Comment by luckykumarirai** [comment]
> Please assign it to me.

i have already assign to you @abhinav5481 plz check above comment.
