### ISSUE TITLE
add a single command to run server with client together

### ISSUE THREAD

**Issue by luckykumarirai** [luckykumarirai/easy-education#5]
Currently, we need two commands to start the project using ```nodemon``` or ```node index.js``` for the server and ```npm start``` for the client. We want a single command ```npm start```  which should start both the server and the client.

**Comment by Devenkapoor7303** [comment]
Can I work on this issue

**Comment by Devenkapoor7303** [comment]
As a part of crosswoc can u assign it to me

**Comment by luckykumarirai** [comment]
Go ahead!
