### ISSUE TITLE
Create Contactus button that would route to contact page.

### ISSUE THREAD

**Issue by abhinav5481** [luckykumarirai/easy-education#51]
## Reason or Problem
The contact button is missing

## Proposal or Solution
Add a contact button and route it to the contact page.

**Comment by abhinav5481** [comment]
Hi @luckykumarirai 
I would like to work on it, please assign it to me.

**Comment by luckykumarirai** [comment]
actually one contact form is available  in navbar, need to some changes on that.

**Comment by luckykumarirai** [comment]
actually one contact form is available  in navbar, need to some changes on that.

**Comment by luckykumarirai** [comment]
actually one contact form is available  in navbar, need to some changes on that.

**Comment by luckykumarirai** [comment]
actually one contact form is available  in navbar, need to some changes on that.

**Comment by abhinav5481** [comment]
Well at this point in time, I can't see any contact form on navbar. 
Anyways if no one is working on it then please assign it to me I will do that.

**Comment by luckykumarirai** [comment]
if you are interested to change contact form of navbar add this to database.
you have rise 2 issue first for design part
second to integrate with database i think you have already done this part.

**Comment by luckykumarirai** [comment]
after that we will remove this contact form.

**Comment by abhinav5481** [comment]
Okay, so you want me to integrate the `contact us` form of navbar with the database right?

**Comment by luckykumarirai** [comment]
there are some iisue in design part of form that available on navbar

**Comment by abhinav5481** [comment]
I am not able to find any `contact form` on the navbar.
![image](https://user-images.githubusercontent.com/60434542/110900103-3a997c80-8328-11eb-96df-5e790052ef31.png)

But there is a form on the footer. Are you referring to this form?
![image](https://user-images.githubusercontent.com/60434542/110900165-53a22d80-8328-11eb-83a2-12894935bda6.png)

**Comment by luckykumarirai** [comment]
> I am not able to find any `contact form` on the navbar.
> ![image](https://user-images.githubusercontent.com/60434542/110900103-3a997c80-8328-11eb-96df-5e790052ef31.png)
> 
> But there is a form on the footer. Are you referring to this form?
> ![image](https://user-images.githubusercontent.com/60434542/110900165-53a22d80-8328-11eb-83a2-12894935bda6.png)

sorry yes in footer one form is already available with 2 Fields.it should be only email and message with submit button.

**Comment by abhinav5481** [comment]
Okay. I can fix it & integrate it to the database as well. Can I work on it?

**Comment by luckykumarirai** [comment]
first rise issue for design part after making PR. rise another issue for database integration.

**Comment by luckykumarirai** [comment]
i will assign both issue to you.

**Comment by abhinav5481** [comment]
Okay

**Comment by luckykumarirai** [comment]
@abhinav5481 make commnet.i have rised the issue regarding this. then i will assign to you.
