### ISSUE TITLE
Add logout button in navbar

### ISSUE THREAD

**Issue by luckykumarirai** [luckykumarirai/easy-education#52]
## Is your feature request related to a problem? Please describe.
Add logout button in navbar that show after signin.and after click on logout button logout the user and  redirect to home page.

**Comment by abhinav5481** [comment]
Hi @luckykumarirai 
I would like to contribute to this issue, please assign it to me

**Comment by luckykumarirai** [comment]
@abhinav5481 i have already assign 2 issues to you.so right now i can not assign more  issue to same person.

**Comment by abhinav5481** [comment]
Hi @luckykumarirai 
Can I get assigned to it now?

**Comment by luckykumarirai** [comment]
@abhinav5481 sure Go ahead!
