### ISSUE TITLE
Integrate the `contact` form of footer, with the database

### ISSUE THREAD

**Issue by abhinav5481** [luckykumarirai/easy-education#56]
## Is your feature request related to a problem? Please describe.
Currently, the `contactUs` form of the footer is non-functional. Integrating it with the backend is required.

## Describe the solution you'd like
Integrate the form data with MongoDB.

**Comment by abhinav5481** [comment]
Hi @luckykumarirai ,
I would like to work on this issue. Could you please assign it to me?

**Comment by luckykumarirai** [comment]
@abhinav5481 Go ahead
