### ISSUE TITLE
Integrate the signup - signin page data of teacher with the databse

### ISSUE THREAD

**Issue by abhinav5481** [luckykumarirai/easy-education#58]
## Is your feature request related to a problem? Please describe.
The front-end part of signin & signup page has not been integrated with the database. This feature needs to be completed to to enhance the utility

## Describe the solution you'd like
Integrate the teacher data with the backend.

**Comment by abhinav5481** [comment]
Hi @luckykumarirai 
I would like to work on this issue. Please assign it to me.

**Comment by luckykumarirai** [comment]
@abhinav5481 Go ahead!
