### ISSUE TITLE
Design signup and signin form

### ISSUE THREAD

**Issue by luckykumarirai** [luckykumarirai/easy-education#6]
Design signup and sign-in form with basic details using react-bootstrap.

**Comment by Hritikkumar** [comment]
Hi Sir, I would like to contribute to this issue. Please assign it to me.

**Comment by abhinav5481** [comment]
Hi,
I would like to work on it as a part of CrossWoc 2021.  Could you please assign this to me?

**Comment by arbazalam01** [comment]
I would like to work on this task

**Comment by luckykumarirai** [comment]
@abhinav5481 Go ahead!

**Comment by abhinav5481** [comment]
I will be using react-router for signup-sign in. Will that be fine?

**Comment by luckykumarirai** [comment]
> I will be using react-router for signup-sign in. Will that be fine?

Yes
