### ISSUE TITLE
Add constraints for teacher signup & Signin page

### ISSUE THREAD

**Issue by abhinav5481** [luckykumarirai/easy-education#60]
## Is your feature request related to a problem? Please describe.
Add constraints for signup & sign in data. This would validate the data before sending it to the database.

## Describe the solution you'd like
All the constraints should be put in the server-side code.

## Additional context
NA

**Comment by abhinav5481** [comment]
Hi @luckykumarirai 
I would like to work on it. Please assign it to me.

**Comment by abhinav5481** [comment]
Hi @luckykumarirai 
can I get assigned to it?

**Comment by luckykumarirai** [comment]
@abhinav5481 Go ahead
