### ISSUE TITLE
Signup Signin button for Student not Working

### ISSUE THREAD

**Issue by abhinav5481** [luckykumarirai/easy-education#62]
**Describe the bug**
Signup Signin button for Student not Working

**Expected behavior**
On clicking the signup or signin page user should get redirected to the respective page

**Impact**
Student will not be able to register for the website

**Comment by abhinav5481** [comment]
Hi @luckykumarirai 
Please assign it to me.

**Comment by abhinav5481** [comment]
Hi @luckykumarirai
Please assign it to me. As tomorrow at 12:00 noon is the deadline for CrossWoc.

**Comment by luckykumarirai** [comment]
Go ahead

**Comment by abhinav5481** [comment]
Hi @luckykumarirai 
Please merge my PR. Today 12:00 midnight is the deadline
