### ISSUE TITLE
add links and some more badges to the README 

### ISSUE THREAD

**Issue by Umesh-01** [luckykumarirai/easy-education#67]
## 📚 Documentation
I will add links to the badges so that it can help them to navigate to different sections/ webpages like PRs, issues, contributors, etc. I will align them to the center and make them of single type so that it will look more interactive and awesome, since the badges will be colorful and more attractive than the text the users will like it.

![image](https://user-images.githubusercontent.com/83420185/124013821-6ab47a80-da00-11eb-9ea1-102392f662aa.png)

See this image, the badge are of no use after clicking on them...

![image](https://user-images.githubusercontent.com/83420185/124013755-54a6ba00-da00-11eb-9ffa-72ed19f54032.png)

## Have you spent some time to check if this issue has been raised before?

Yes

### Have you read the [Code of Conduct](https://github.com/luckykumarirai/easy-education/blob/master/CODE_OF_CONDUCT.md)?

Yes

**Comment by Umesh-01** [comment]
@luckykumarirai should I make these changes??

**Comment by luckykumarirai** [comment]
@Umesh-01 Go ahead!
