### ISSUE TITLE
Design an AboutUs

### ISSUE THREAD

**Issue by luckykumarirai** [luckykumarirai/easy-education#8]
Design an AboutUs using react-bootstrap.

**Comment by khushi935** [comment]
I want to work on this. Can you please assign it to me?

**Comment by luckykumarirai** [comment]
@khushi935 Go ahead!

**Comment by khushi935** [comment]
Can you just guide me how about us should look like?

**Comment by luckykumarirai** [comment]
Just make with dummy data right now with better UI.

**Comment by khushi935** [comment]
okay thank you.

**Comment by khushi935** [comment]
https://user-images.githubusercontent.com/62712155/107937886-929fc600-6faa-11eb-805e-4b4142c26bab.mp4

Does this look good?

**Comment by luckykumarirai** [comment]
> Does this look good?

Choose some attractive colors for both boxes. I think by mistake you make changes in  Footer design so content align right.
It should not happen. Otherwise, it is fine.

**Comment by khushi935** [comment]
![Screenshot (79)](https://user-images.githubusercontent.com/62712155/107955629-026e7a80-6fc4-11eb-82d7-db28c7ecb2dd.png)
I align the footer text center again. Now have a look.

**Comment by luckykumarirai** [comment]
> ![Screenshot (79)](https://user-images.githubusercontent.com/62712155/107955629-026e7a80-6fc4-11eb-82d7-db28c7ecb2dd.png)
> I align the footer text center again. Now have a look.

okay, that fine make PR.
